# Generated by Django 5.2 on 2025-05-27 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_complete_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoahorro',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='periodicidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
