# Generated by Django 5.2 on 2025-05-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_objetivoahorro_completado_alter_transaccion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierecurrente',
            name='ultima_generada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
