# Generated by Django 5.2 on 2025-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_serierecurrente_transaccion_es_recurrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, null=True),
        ),
    ]
