# Generated by Django 5.2 on 2025-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
